[package]
name = "rust_slurm"
version = "0.1.0"
edition = "2021"


[dependencies]
anyhow = "1.0.89"
tokio = {version = "1",  features = ["io-std"]}
async-ssh2-tokio = "0.8.12"
chrono = {version = "0.4.38", features = ["serde"]}
serde = { version = "1.0", features = ["derive"] }
serde_json = "1"
glob = "0.3.1"
structdiff = {version = "0.7.1", features = ["serde","debug_diffs"]}